ROClothing/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ROClothing.Data.Repository.IRepository;
using ROClothing.Models;
using ROClothing.Models.ViewModels;

namespace ROClothing.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ProductController : Controller
	{
		private readonly IUnitOfWork _dbContext;
		public readonly IWebHostEnvironment _hostEnvironment;
		public ProductController(IUnitOfWork dbContext, IWebHostEnvironment hostEnvironment)
		{
			_dbContext = dbContext;
			_hostEnvironment = hostEnvironment;
		}
		public IActionResult Index()
		{
			IEnumerable<Product> productList = _dbContext.ProductRepo.GetAll(includeProperties: "Category");
			return View(productList);
		}
		public IActionResult Upsert(int? id)
		{
			//Creates View model that binds Product with Category and Product type
			ProductVM productVM = new()
			{
				Product = new(),
				categories = _dbContext.CategoryRepo.GetAll().Select(c => new SelectListItem
				{
					Text = c.CategoryName,
					Value = c.Id.ToString(),
				}),

				productTypes = _dbContext.ProductTypeRepo.GetAll().Select(c => new SelectListItem
				{
					Text = c.ProductTypeName,
					Value = c.Id.ToString(),
				}),
			};

			if (id == null || id == 0)
			{
				return View(productVM);
				//return PartialView("_UpsertPartial", new Product());

			}
			else
			{
				productVM.Product = _dbContext.ProductRepo.FindFirst(c => c.Id == id);
				return View(productVM);
				//return PartialView("_UpsertPartial", productVM.Product);

			}
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(ProductVM productVM, IFormFile? productImg)
		{
			if (ModelState.IsValid)
			{
				var webrootpath = _hostEnvironment.WebRootPath;

				if (productImg != null)
				{
					var uploads = Path.Combine(webrootpath, @"images\productImages");
					var filename = Guid.NewGuid().ToString();
					var extension = Path.GetExtension(productImg.FileName);

					//delete old image
					if (productVM.Product.ProductImage != null)
					{
						var oldImage = Path.Combine(webrootpath, productVM.Product.ProductImage.TrimStart('\\'));
						if (System.IO.File.Exists(oldImage))
						{
							System.IO.File.Delete(oldImage);
						}
					}

					//add new image
					using (var filestreams = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
					{
						productImg.CopyTo(filestreams);
					}
					productVM.Product.ProductImage = @"\images\productImages\" + filename + extension;
				}

				if (productVM.Product.Id == 0)
				{
					_dbContext.ProductRepo.Add(productVM.Product);
				}
				else
				{
					_dbContext.ProductRepo.Update(productVM.Product);
				}
				_dbContext.Save();
				TempData["Success"] = "Successfully created new product";
			}


			return RedirectToAction("Index");
		}



		public IActionResult Delete(int id)
		{
			ProductVM productVm = new();
			productVm.Product = _dbContext.ProductRepo.FindFirst(x => x.Id == id);
			return View(productVm);
		}

		[HttpPost]
		public IActionResult Delete(ProductVM productVM, IFormFile? productImg)
		{
			if (ModelState.IsValid)
			{
				var webrootpath = _hostEnvironment.WebRootPath;

		  
					//delete image

						var oldImage = Path.Combine(webrootpath, productVM.Product.ProductImage.TrimStart('\\'));
						if (System.IO.File.Exists(oldImage))
						{
							System.IO.File.Delete(oldImage);
						}
 
					

			   
				_dbContext.ProductRepo.Remove(productVM.Product);
				_dbContext.Save();
				TempData["Success"] = "Successfully created new product";
			}


			return RedirectToAction("Index");
		}
	}
}

ROClothing/Areas/Admin/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ROClothing.Data.Repository.IRepository;
using ROClothing.Models;

namespace ROClothing.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ProductTypeController : Controller
	{
		private readonly IUnitOfWork _dbContext;
		private readonly IWebHostEnvironment _hostEnvironment;

		public ProductTypeController(IUnitOfWork dbContext, IWebHostEnvironment hostEnvironment)
		{
			_dbContext = dbContext;
			_hostEnvironment = hostEnvironment;
		}
		public IActionResult Index()
		{
			IEnumerable<ProductType> productTypeList = _dbContext.ProductTypeRepo.GetAll();
			return View(productTypeList);
		}

		public IActionResult Upsert(int? id)
		{
			if (id == null || id == 0)
			{
				//create product type
				var productTypeItem = new ProductType();
				return View(productTypeItem);
			}
			else
			{
				//edit item
				var productTypeItem = _dbContext.ProductTypeRepo.FindFirst(u => u.Id == id);
				return View(productTypeItem);
			}
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(ProductType productTypeItem, IFormFile? productTypeImg)
		{
			if (ModelState.IsValid)
			{
				var webrootpath = _hostEnvironment.WebRootPath;

				if (productTypeImg != null)
				{
					var uploads = Path.Combine(webrootpath, @"images\productTypeImages");
					var filename = Guid.NewGuid().ToString();
					var extension = Path.GetExtension(productTypeImg.FileName);


					//delete old Image
					if (productTypeItem.ProductTypeImage != null)
					{
						var oldImagePath = Path.Combine(webrootpath, productTypeItem.ProductTypeImage.TrimStart('\\'));
						if (System.IO.File.Exists(oldImagePath))
						{
							System.IO.File.Delete(oldImagePath);
						}
					}

					//Adding new Image
					using (var filestreams = new FileStream(Path.Combine(uploads, filename + extension), FileMode.Create))
					{
						productTypeImg.CopyTo(filestreams);
					}

					productTypeItem.ProductTypeImage = @"\images\productTypeImages\" + filename + extension;
				}

				if (productTypeItem.Id == 0)
				{
					_dbContext.ProductTypeRepo.Add(productTypeItem);
				}
				else
				{
					_dbContext.ProductTypeRepo.Update(productTypeItem);
				}

				_dbContext.Save();
				TempData["Success"] = "Successfully created product type";
				return RedirectToAction("Index");
			}
			else
			{
				return View(productTypeItem);
			}
		}

		public IActionResult Delete(int id)
		{
			var webrootpath = _hostEnvironment.WebRootPath;
			var productTypefromDb = _dbContext.ProductTypeRepo.FindFirst(x => x.Id == id);

			var oldImagePath = Path.Combine(webrootpath, productTypefromDb.ProductTypeImage.TrimStart('\\'));

			if (System.IO.File.Exists(oldImagePath))
			{
				System.IO.File.Delete(oldImagePath);
			}
			_dbContext.ProductTypeRepo.Remove(productTypefromDb);
			_dbContext.Save();

			return RedirectToAction("Index");
		}
	}
}

ROClothing/Areas/Customer/Controllers/CProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ROClothing.Data.Repository.IRepository;
using ROClothing.Models;
using ROClothing.Models.ViewModels;
using System.Security.Claims;

namespace ROClothing.Areas.Admin.Controllers
{
	[Area("Customer")]
	public class CProductController : Controller
	{
		[BindProperty]
		public ShoppingCart cartItems { get; set; }
		private readonly IUnitOfWork _dbContext;
		public CProductController(IUnitOfWork dbContext)
		{
			_dbContext = dbContext;
		}
		public IActionResult Index()
		{
			IEnumerable<Product> productList = _dbContext.ProductRepo.GetAll(includeProperties: "Category");
			return View(productList);
		}

		public IActionResult Details(int ProductId)
		{
			cartItems = new()
			{
				NoOfItems = 1,
				ProductId = ProductId,
				Product = _dbContext.ProductRepo.FindFirst(x => x.Id == ProductId, includeProperties: "Category"),
			};
			return View(cartItems);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize]
		public IActionResult Details(ShoppingCart shoppingCart)
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			shoppingCart.ApplicationUserId = claim.Value;

			var cartFromDb = _dbContext.ShoppingCartRepo.FindFirst(x => x.ProductId == shoppingCart.ProductId);

			if (cartFromDb == null)
			{
				_dbContext.ShoppingCartRepo.Add(shoppingCart);
			}
			else
			{
				_dbContext.ShoppingCartRepo.IncrementShoppingCart(cartFromDb, shoppingCart.NoOfItems);
			}
			_dbContext.Save();



			return RedirectToAction(nameof(Index));
		}
	}
}

ROClothing/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ROClothing.Data.Repository.IRepository;
using ROClothing.Models.ViewModels;
using System.Security.Claims;

namespace ROClothing.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartVM shoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            shoppingCartVM = new()
            {
                cartList = _unitOfWork.ShoppingCartRepo.GetAll(x => x.ApplicationUserId == claim.Value, includeProperties: "Product"),
            };

            foreach (var item in shoppingCartVM.cartList)
            {
                shoppingCartVM.cartTotal += (item.Product.Price * item.NoOfItems);
            }

            return View(shoppingCartVM);
        }


        public IActionResult MinusCartItem(int cartId) 
        {
            var cart = _unitOfWork.ShoppingCartRepo.FindFirst(x => x.Id == cartId);

            if (cart.NoOfItems <= 1)
            {
                _unitOfWork.ShoppingCartRepo.Remove(cart);
            }
            else
            {
                _unitOfWork.ShoppingCartRepo.DecrementShoppingCart(cart, 1);
            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult PlusCartItem(int cartId)
        {
            var cart = _unitOfWork.ShoppingCartRepo.FindFirst(x => x.Id == cartId);
            
            if (cart.NoOfItems >= 1000)
            {
                cart.NoOfItems = 1000;
            }
            else
            {
                _unitOfWork.ShoppingCartRepo.IncrementShoppingCart(cart, 1);

            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveCartItem(int cartId)
        {
            var cart = _unitOfWork.ShoppingCartRepo.FindFirst(x => x.Id == cartId);
            _unitOfWork.ShoppingCartRepo.Remove(cart);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

ROClothing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ROClothing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ROClothing.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="topmost-header bg-black text-center p-2">
            <p class="text-light">Get Up to 40% OFF New Clothing Deals <span>* Limited time only</span></p>
        </div>

        <!--  -----     Before Navigation ---------    -->
        <div class="container">
            <div class="phone-logo-group">
                <div class="col phone-group">
                    <i class="bi bi-telephone-fill"></i>
                    <div class="phone-no-group">
                        <p><span>CALL US NOW</span><br />
                        +123 4567 890</p>
                    </div>
                </div>

                <div class="col logo-container">
                    <a asp-controller="Home" asp-action="Index"><img src="~/images/pageimages/reenclothing.png" /></a>
                </div>
                <div class="col text-end">
                    <div class="top-icons">
                        <i class="bi bi-person"></i>
                        <i class="bi bi-search"></i>
                        <a asp-controller="Cart" asp-action="Index"><i class="bi bi-cart-plus"></i></a>
                    </div>
                </div>
            </div>
        </div>


        <!--  -----     Navigation ---------    -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="CProduct" asp-action="Index">PRODUCTS</a>
                        </li>
                    </ul>
                    
                    @if (User.IsInRole(@UtilitySD.SuperUser))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type</a></li>
                                </ul>
                            </li>
                        </ul>

                    }


                    <partial name="_LoginPartial" />
                   
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

     <footer class="bg-dark my-footer text-light">
        <div class="container">
            <div class="row footer-content">
                <div class="col-lg">
                    <h4>CONTACT INFO</h4>

                    <p>PHONE: <br />+123 4567 890</p>
                    <p>EMAIL: <br />career.oguchemaureen@gmail.com</p>

                    <div class="social-icons mt-4">
                        <a href="https://www.twitter.com/MaureenMOguche" target="_blank"><i class="bi bi-twitter"></i></a>
                        <a href="https://www.likedin.com/in/maureenoguche" target="_blank"><i class="bi bi-linkedin"></i></a>
                        <a href="https://github.com/MaureenMOguche"><i class="bi bi-github"></i></a>
                    </div>
                </div>
                <div class="col-lg">
                    <h4>SITE MAP</h4>
                    <a href="#">About Us</a><br />
                    <a href="#">Special Offers</a><br />
                    <a href="#">My Account</a><br />
                    <a href="#">Order History</a><br />

                </div>
                <div class="col-lg">
                    <h4>SUBSCRIBE TO NEWSLETTER</h4>
                    <p>Get all the latest information on events, sales and offers. Sign up for newsletter:</p>
                    <form method="post">
                        <div class="subscribe">
                            <input type ="text" placeholder="Email Address"/>
                            <button class="btn-subscribe">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <hr class="mt-5"/>

            <div class="row">
                <div class="col">
                    <p>&copy; Reen Clothing. Designed and Developed by 
                        <a href="https://github.com/MaureenMOguche">
                            Maureen Oguche</a>.<br />
                            <a href="https://wa.link/sy0vzi" target="_blank">
                                <i class="bi bi-whatsapp"></i>
                                08030411314</a>
                    </p>

                </div>
                <div class="col">
                    <div class="row">
                        <div class="col-7"></div>
                        <div class="col-3">
                            <img src="~/images/pageImages/Paystack.png" class="img-fluid"/>
                        </div>
                        <div class="col-2">
                            <img src="~/images/pageImages/stripe.png" class="img-fluid" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>